// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NISA.DataAccessLayer;

#nullable disable

namespace NISA.DataAccessLayer.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230714173835_migOne")]
    partial class migOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NISA.Model.AttachmentDetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("fileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<int>("ticketId")
                        .HasColumnType("int");

                    b.Property<string>("uploadedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("attachmentDetails");
                });

            modelBuilder.Entity("NISA.Model.LookUpTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("lookUpTables");
                });

            modelBuilder.Entity("NISA.Model.TicketDetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("age")
                        .HasColumnType("int");

                    b.Property<int>("assignedTo")
                        .HasColumnType("int");

                    b.Property<string>("attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("departmentLookUpId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("priotity")
                        .HasColumnType("int");

                    b.Property<int?>("severity")
                        .HasColumnType("int");

                    b.Property<string>("startDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ticketRefnum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("departmentLookUpId");

                    b.HasIndex("userId");

                    b.ToTable("ticketDetails");
                });

            modelBuilder.Entity("NISA.Model.TicketHistoryTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("departmentLookUpRefId")
                        .HasColumnType("int");

                    b.Property<string>("endDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("priority")
                        .HasColumnType("int");

                    b.Property<int?>("severity")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ticketRefNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("departmentLookUpRefId");

                    b.HasIndex("updatedBy");

                    b.ToTable("ticketHistoryTables");
                });

            modelBuilder.Entity("NISA.Model.UserDetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("departmentLookupRefId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("isLoggedIn")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("departmentLookupRefId");

                    b.ToTable("userDetails");
                });

            modelBuilder.Entity("NISA.Model.TicketDetails", b =>
                {
                    b.HasOne("NISA.Model.LookUpTable", "LookUpTable")
                        .WithMany()
                        .HasForeignKey("departmentLookUpId");

                    b.HasOne("NISA.Model.UserDetails", "UserDetails")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("LookUpTable");

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("NISA.Model.TicketHistoryTable", b =>
                {
                    b.HasOne("NISA.Model.LookUpTable", "LookUpTable")
                        .WithMany()
                        .HasForeignKey("departmentLookUpRefId");

                    b.HasOne("NISA.Model.UserDetails", "UserDetails")
                        .WithMany()
                        .HasForeignKey("updatedBy");

                    b.Navigation("LookUpTable");

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("NISA.Model.UserDetails", b =>
                {
                    b.HasOne("NISA.Model.LookUpTable", "LookUpTables")
                        .WithMany()
                        .HasForeignKey("departmentLookupRefId");

                    b.Navigation("LookUpTables");
                });
#pragma warning restore 612, 618
        }
    }
}
